spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 44df5b0e84e42359df75
            client-secret: e16ece682fed3977cb502da20acf68654da028cc
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize  #  ??????????
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user


